/*
 * ojjyOS v3 Kernel - Main Entry Point
 *
 * M2: Filesystem milestone
 */

#include "types.h"
#include "boot_info.h"
#include "serial.h"
#include "framebuffer.h"
#include "console.h"
#include "string.h"
#include "gdt.h"
#include "idt.h"
#include "memory.h"
#include "paging.h"
#include "timer.h"
#include "panic.h"
#include "font.h"

/* Driver subsystem */
#include "drivers/driver.h"
#include "drivers/input.h"
#include "drivers/ps2_keyboard.h"
#include "drivers/ps2_mouse.h"
#include "drivers/ata.h"
#include "drivers/rtc.h"
#include "drivers/block_cache.h"
#include "drivers/diagnostics.h"

/* Filesystem */
#include "fs/vfs.h"
#include "fs/ojfs.h"
#include "fs/bundle.h"
#include "fs/ramfs.h"

/* UI compositor */
#include "ui/compositor.h"

/* Embedded filesystem (generated by mkfs.sh) */
#include "fs/system_fs.h"

/* Global boot info pointer */
BootInfo *g_boot_info = NULL;

/* Version info */
#define OJJYOS_VERSION  "3.0.0-M2"
#define OJJYOS_AUTHOR   "Jonas Lee"

/* OJFS instance */
static OjfsInstance *root_fs = NULL;

static size_t str_append(char *dest, size_t size, const char *src)
{
    size_t len = strlen(dest);
    size_t i = 0;
    if (len >= size) return len;
    while (src[i] && (len + i + 1) < size) {
        dest[len + i] = src[i];
        i++;
    }
    dest[len + i] = '\0';
    return len + i;
}

/* UI state */
static bool ui_mode = false;
static bool ui_initialized = false;
static bool ui_demo_created = false;

/*
 * About app handler (builtin)
 */
static void about_app_handler(Bundle *bundle)
{
    (void)bundle;

    console_printf("\n");
    console_printf("========================================\n");
    console_printf("          About ojjyOS\n");
    console_printf("========================================\n\n");

    console_printf("  Version:  %s\n", OJJYOS_VERSION);
    console_printf("  Author:   %s\n", OJJYOS_AUTHOR);
    console_printf("\n");

    console_printf("  A custom operating system with\n");
    console_printf("  macOS Tahoe-inspired UI.\n");
    console_printf("\n");

    console_printf("  Built from scratch - not based on\n");
    console_printf("  Linux, BSD, Windows, or macOS.\n");
    console_printf("\n");

    /* Show system info */
    console_printf("  Display:  %dx%d\n", fb_get_width(), fb_get_height());
    console_printf("  Memory:   %d MB\n",
        (int)(pmm_get_total_memory() / (1024 * 1024)));

    console_printf("\n========================================\n\n");
}

/*
 * List directory contents
 */
static void cmd_ls(const char *path)
{
    if (!path || path[0] == '\0') {
        path = "/";
    }

    VfsDir *dir = vfs_opendir(path);
    if (!dir) {
        console_printf("Cannot open directory: %s\n", path);
        return;
    }

    console_printf("\nContents of %s:\n", path);
    console_printf("----------------------------------------\n");

    VfsDirEntry entry;
    int count = 0;

    while (vfs_readdir(dir, &entry) == 0) {
        const char *type_str;
        switch (entry.type) {
            case VFS_TYPE_DIR:    type_str = "DIR "; break;
            case VFS_TYPE_BUNDLE: type_str = "APP "; break;
            case VFS_TYPE_FILE:   type_str = "FILE"; break;
            default:              type_str = "??? "; break;
        }

        if (entry.type == VFS_TYPE_FILE) {
            console_printf("  [%s]  %-24s  %d bytes\n",
                type_str, entry.name, (int)entry.size);
        } else {
            console_printf("  [%s]  %s/\n", type_str, entry.name);
        }
        count++;
    }

    vfs_closedir(dir);
    console_printf("----------------------------------------\n");
    console_printf("%d items\n\n", count);
}

/*
 * Read and display a text file
 */
static void cmd_cat(const char *path)
{
    if (!path || path[0] == '\0') {
        console_printf("Usage: cat <path>\n");
        return;
    }

    VfsFile *file = vfs_open(path, VFS_O_READ);
    if (!file) {
        console_printf("Cannot open file: %s\n", path);
        return;
    }

    console_printf("\n--- %s ---\n", path);

    char buffer[256];
    ssize_t bytes;
    while ((bytes = vfs_read(file, buffer, sizeof(buffer) - 1)) > 0) {
        buffer[bytes] = '\0';
        console_printf("%s", buffer);
    }

    console_printf("\n--- end ---\n\n");
    vfs_close(file);
}

/*
 * Launch an application
 */
static void cmd_launch(const char *path)
{
    if (!path || path[0] == '\0') {
        console_printf("Usage: launch <app.app>\n");
        return;
    }

    /* Build full path if needed */
    char full_path[BUNDLE_PATH_MAX];
    if (path[0] != '/') {
        vfs_join_path(full_path, sizeof(full_path), "/Applications", path);
    } else {
        strncpy(full_path, path, sizeof(full_path) - 1);
    }

    Bundle bundle;
    if (bundle_load(full_path, &bundle) != 0) {
        console_printf("Cannot load bundle: %s\n", full_path);
        return;
    }

    bundle_launch(&bundle);
}

/*
 * List applications
 */
static void cmd_apps(void)
{
    Bundle bundles[16];
    int count = bundle_list_directory("/Applications", bundles, 16);

    console_printf("\n=== Applications ===\n");
    for (int i = 0; i < count; i++) {
        console_printf("  %s  (v%s)\n",
            bundles[i].manifest.name,
            bundles[i].manifest.version);
    }
    console_printf("\n%d app(s) found\n\n", count);
}

/*
 * Show help
 */
static void cmd_help(void)
{
    console_printf("\nCommands:\n");
    console_printf("  ls [path]      - List directory contents\n");
    console_printf("  cat <file>     - Display file contents\n");
    console_printf("  apps           - List applications\n");
    console_printf("  launch <app>   - Launch an application\n");
    console_printf("  ui [dark]      - Start Tahoe UI demo\n");
    console_printf("  about          - Show About ojjyOS\n");
    console_printf("  diag           - Show diagnostics\n");
    console_printf("  time           - Show current time\n");
    console_printf("  tree           - Show filesystem tree\n");
    console_printf("  help           - Show this help\n");
    console_printf("\n");
}

/*
 * Start UI demo
 */
static void cmd_ui(const char *arg)
{
    if (!ui_initialized) {
        compositor_init(fb_get_width(), fb_get_height());
        ui_initialized = true;
    }

    bool use_dark = (arg && strcmp(arg, "dark") == 0);
    compositor_set_dark_mode(use_dark);
    compositor_set_wallpaper(use_dark ? "/System/Wallpapers/Tahoe Dark.raw"
                                      : "/System/Wallpapers/Tahoe Light.raw");

    if (!ui_demo_created) {
        int win = compositor_create_window("Tahoe Glass", 140, 120, 520, 360);
        if (win >= 0) {
            compositor_set_demo(win, true);
            ui_demo_created = true;
        }
    }

    compositor_set_active_app("Finder");
    compositor_open_default_apps();

    ui_mode = true;
    console_clear();
}

/*
 * Simple command parser
 */
static char cmd_buffer[256];
static int cmd_pos = 0;

static void process_command(void)
{
    cmd_buffer[cmd_pos] = '\0';

    /* Skip empty commands */
    if (cmd_pos == 0) {
        return;
    }

    /* Parse command and argument */
    char *cmd = cmd_buffer;
    char *arg = NULL;

    /* Skip leading spaces */
    while (*cmd == ' ') cmd++;

    /* Find argument */
    for (char *p = cmd; *p; p++) {
        if (*p == ' ') {
            *p = '\0';
            arg = p + 1;
            while (*arg == ' ') arg++;
            break;
        }
    }

    /* Execute command */
    if (strcmp(cmd, "ls") == 0) {
        cmd_ls(arg);
    } else if (strcmp(cmd, "cat") == 0) {
        cmd_cat(arg);
    } else if (strcmp(cmd, "apps") == 0) {
        cmd_apps();
    } else if (strcmp(cmd, "launch") == 0) {
        cmd_launch(arg);
    } else if (strcmp(cmd, "ui") == 0) {
        cmd_ui(arg);
    } else if (strcmp(cmd, "about") == 0) {
        about_app_handler(NULL);
    } else if (strcmp(cmd, "diag") == 0) {
        diagnostics_show();
    } else if (strcmp(cmd, "time") == 0) {
        console_printf("\nTime: ");
        rtc_print_time();
        console_printf("\n");
    } else if (strcmp(cmd, "tree") == 0) {
        if (root_fs) {
            ojfs_print_tree(root_fs);
        }
    } else if (strcmp(cmd, "help") == 0 || strcmp(cmd, "?") == 0) {
        cmd_help();
    } else if (cmd[0] != '\0') {
        console_printf("Unknown command: %s\n", cmd);
        console_printf("Type 'help' for available commands.\n");
    }

    cmd_pos = 0;
}

/*
 * Draw boot splash screen
 */
static void draw_splash_screen(void)
{
    uint32_t width = fb_get_width();
    uint32_t height = fb_get_height();

    fb_clear(COLOR_SKY_BLUE);

    int panel_width = 500;
    int panel_height = 200;
    int panel_x = (width - panel_width) / 2;
    int panel_y = (height - panel_height) / 2;

    fb_fill_rect(panel_x + 4, panel_y + 4, panel_width, panel_height,
                 fb_blend(COLOR_SKY_BLUE, COLOR_DEEP_BLUE, 80));
    fb_fill_rect(panel_x, panel_y, panel_width, panel_height,
                 fb_blend(COLOR_SKY_BLUE, COLOR_WHITE, 180));
    fb_draw_rect(panel_x, panel_y, panel_width, panel_height,
                 fb_blend(COLOR_WHITE, COLOR_SKY_BLUE, 128));

    const char *title = "ojjyOS v3";
    int title_x = panel_x + (panel_width - strlen(title) * 8) / 2;
    fb_draw_string(title_x, panel_y + 50, title, COLOR_DEEP_BLUE,
                   fb_blend(COLOR_SKY_BLUE, COLOR_WHITE, 180));

    const char *author = "Created by Jonas Lee";
    int author_x = panel_x + (panel_width - strlen(author) * 8) / 2;
    fb_draw_string(author_x, panel_y + 90, author, COLOR_ROYAL_BLUE,
                   fb_blend(COLOR_SKY_BLUE, COLOR_WHITE, 180));

    char version_str[64];
    strcpy(version_str, "Version ");
    strncpy(version_str + 8, OJJYOS_VERSION, sizeof(version_str) - 9);
    int version_x = panel_x + (panel_width - strlen(version_str) * 8) / 2;
    fb_draw_string(version_x, panel_y + 130, version_str, COLOR_SLATE,
                   fb_blend(COLOR_SKY_BLUE, COLOR_WHITE, 180));
}

/*
 * Draw mouse cursor
 */
static void draw_cursor(int x, int y)
{
    static const uint8_t cursor[12] = {
        0x80, 0xC0, 0xE0, 0xF0, 0xF8, 0xFC,
        0xFE, 0xF0, 0xD8, 0x8C, 0x0C, 0x06
    };

    for (int row = 0; row < 12; row++) {
        for (int col = 0; col < 8; col++) {
            if (cursor[row] & (0x80 >> col)) {
                fb_put_pixel(x + col, y + row, COLOR_BLACK);
            }
        }
    }
    for (int row = 1; row < 11; row++) {
        for (int col = 1; col < 7; col++) {
            uint8_t inner = cursor[row] & (0x80 >> col);
            uint8_t left = cursor[row] & (0x80 >> (col - 1));
            if (inner && left) {
                fb_put_pixel(x + col, y + row, COLOR_WHITE);
            }
        }
    }
}

/*
 * Kernel main function
 */
void kernel_main(BootInfo *boot_info)
{
    g_boot_info = boot_info;

    /* Initialize serial first for debugging */
    serial_init(COM1_PORT);
    serial_printf("\n\n");
    serial_printf("========================================\n");
    serial_printf("  ojjyOS v3 Kernel Starting\n");
    serial_printf("  Version: %s\n", OJJYOS_VERSION);
    serial_printf("  Author:  %s\n", OJJYOS_AUTHOR);
    serial_printf("========================================\n\n");

    serial_printf("[BOOT] Framebuffer: %dx%d @ 0x%p\n",
        boot_info->fb_width, boot_info->fb_height, boot_info->fb_addr);

    /* Initialize framebuffer */
    fb_init(boot_info);
    draw_splash_screen();
    for (volatile int i = 0; i < 30000000; i++) {}

    /* Initialize console */
    console_init();
    console_set_colors(COLOR_TEXT, COLOR_CREAM);
    console_clear();

    console_printf("ojjyOS v3 - Version %s\n", OJJYOS_VERSION);
    console_printf("Created by %s\n", OJJYOS_AUTHOR);
    console_printf("========================================\n\n");

    /* Core initialization */
    console_printf("Initializing GDT...\n");
    gdt_init();

    console_printf("Initializing IDT...\n");
    idt_init();

    console_printf("Initializing memory manager...\n");
    pmm_init(boot_info);
    console_printf("  Total: %d MB, Free: %d MB\n",
        (int)(pmm_get_total_memory() / (1024 * 1024)),
        (int)(pmm_get_free_memory() / (1024 * 1024)));

    console_printf("Initializing paging...\n");
    paging_init();

    console_printf("Initializing timer...\n");
    timer_init();

    /* Driver subsystem */
    console_printf("Initializing driver subsystem...\n");
    driver_subsystem_init();

    console_printf("Initializing input subsystem...\n");
    input_init();
    input_set_mouse_bounds(fb_get_width(), fb_get_height());

    console_printf("Registering drivers...\n");
    ps2_keyboard_init();
    ps2_mouse_init();
    ata_init();
    rtc_init();

    console_printf("Probing drivers...\n");
    driver_probe_all();

    console_printf("Initializing block cache...\n");
    block_cache_init();

    /* Initialize filesystem */
    console_printf("Initializing VFS...\n");
    vfs_init();

    console_printf("Mounting root filesystem...\n");
    VfsOps *fs_ops = ojfs_init(embedded_fs, embedded_fs_len, &root_fs);
    if (fs_ops) {
        vfs_mount("/", fs_ops, root_fs, true);
        console_printf("  Root filesystem mounted (OJFS, %d bytes)\n",
            (int)embedded_fs_len);
    } else {
        console_printf("  WARNING: Failed to mount root filesystem\n");
    }

    console_printf("Mounting RAM filesystem for user data...\n");
    VfsOps *ram_ops = ramfs_init();
    if (ram_ops) {
        vfs_mount("/Users", ram_ops, NULL, false);
        vfs_mount("/Library", ram_ops, NULL, false);

        vfs_mkdir("/Users/guest");
        vfs_mkdir("/Users/guest/Desktop");
        vfs_mkdir("/Users/guest/Documents");
        vfs_mkdir("/Library/Preferences");

        VfsFile *wf = vfs_open("/Users/guest/Desktop/Welcome.txt", VFS_O_CREATE | VFS_O_WRITE | VFS_O_TRUNC);
        if (wf) {
            const char *msg = "Welcome to ojjyOS!\n";
            vfs_write(wf, msg, strlen(msg));
            vfs_close(wf);
        }

        VfsFile *tf = vfs_open("/Users/guest/Documents/Test.txt", VFS_O_CREATE | VFS_O_WRITE | VFS_O_TRUNC);
        if (tf) {
            const char *msg = "This is a test document.\n";
            vfs_write(tf, msg, strlen(msg));
            vfs_close(tf);
        }

        VfsFile *nf = vfs_open("/Users/guest/Documents/Notes.txt", VFS_O_CREATE | VFS_O_WRITE | VFS_O_TRUNC);
        if (nf) {
            const char *msg = "- Welcome to Notes\n- Start writing here\n";
            vfs_write(nf, msg, strlen(msg));
            vfs_close(nf);
        }

        VfsFile *cf = vfs_open("/Users/guest/Documents/Calendar.txt", VFS_O_CREATE | VFS_O_WRITE | VFS_O_TRUNC);
        if (cf) {
            RtcTime now;
            rtc_read_time(&now);
            char line[128];
            char num[16];

            line[0] = '\0';
            utoa(now.year, num, 10);
            str_append(line, sizeof(line), num);
            str_append(line, sizeof(line), "-");
            if (now.month < 10) str_append(line, sizeof(line), "0");
            utoa(now.month, num, 10);
            str_append(line, sizeof(line), num);
            str_append(line, sizeof(line), "-");
            if (now.day < 10) str_append(line, sizeof(line), "0");
            utoa(now.day, num, 10);
            str_append(line, sizeof(line), num);
            str_append(line, sizeof(line), "|09:00|Standup|Studio\n");
            vfs_write(cf, line, strlen(line));

            line[0] = '\0';
            utoa(now.year, num, 10);
            str_append(line, sizeof(line), num);
            str_append(line, sizeof(line), "-");
            if (now.month < 10) str_append(line, sizeof(line), "0");
            utoa(now.month, num, 10);
            str_append(line, sizeof(line), num);
            str_append(line, sizeof(line), "-");
            if (now.day < 10) str_append(line, sizeof(line), "0");
            utoa(now.day, num, 10);
            str_append(line, sizeof(line), num);
            str_append(line, sizeof(line), "|13:30|Design Review|Conference\n");
            vfs_write(cf, line, strlen(line));
            vfs_close(cf);
        }
    }

    /* Initialize bundle system */
    console_printf("Initializing bundle system...\n");
    bundle_init();
    bundle_register_builtin("com.ojjyos.about", about_app_handler);

    /* Enable interrupts */
    console_printf("Enabling interrupts...\n");
    interrupts_enable();

    /* Initialization complete */
    console_printf("\n========================================\n");
    console_printf("Kernel initialization complete!\n");
    console_printf("========================================\n\n");

    /* Show available apps */
    cmd_apps();

    /* Show filesystem tree */
    if (root_fs) {
        ojfs_print_tree(root_fs);
    }

    /* Instructions */
    console_printf("Type 'help' for available commands.\n\n");
    console_printf("> ");

    /* Cursor position */
    int32_t last_mx = -100, last_my = -100;

    /* Main loop */
    serial_printf("[INIT] Entering main loop\n");

    while (1) {
        /* Process input events */
        while (input_has_event()) {
            InputEvent event;
            input_poll_event(&event);

            if (ui_mode) {
                switch (event.type) {
                    case INPUT_EVENT_KEY_PRESS:
                        if (event.key.keycode == KEY_ESCAPE && !compositor_overlay_active()) {
                            ui_mode = false;
                            console_clear();
                            console_printf("Type 'help' for available commands.\n\n> ");
                            break;
                        }
                        compositor_handle_key(event.key.keycode, event.key.ascii, event.key.modifiers);
                        break;
                    case INPUT_EVENT_MOUSE_MOVE:
                        compositor_handle_mouse_move(event.motion.dx, event.motion.dy);
                        break;
                    case INPUT_EVENT_MOUSE_BUTTON_DOWN:
                        compositor_handle_mouse(event.button.x, event.button.y, true, false);
                        break;
                    case INPUT_EVENT_MOUSE_BUTTON_UP:
                        compositor_handle_mouse(event.button.x, event.button.y, false, true);
                        break;
                    default:
                        break;
                }
            } else {
                switch (event.type) {
                    case INPUT_EVENT_KEY_PRESS:
                        if (event.key.ascii) {
                            if (event.key.ascii == '\n') {
                                console_putc('\n');
                                process_command();
                                console_printf("> ");
                            } else if (event.key.ascii == '\b') {
                                if (cmd_pos > 0) {
                                    cmd_pos--;
                                    console_putc('\b');
                                }
                            } else if (cmd_pos < (int)sizeof(cmd_buffer) - 1) {
                                cmd_buffer[cmd_pos++] = event.key.ascii;
                                console_putc(event.key.ascii);
                            }
                        }
                        break;

                    case INPUT_EVENT_MOUSE_BUTTON_DOWN:
                        /* Could trigger app launch on click in future */
                        break;

                    default:
                        break;
                }
            }
        }

        if (ui_mode) {
            compositor_tick(timer_get_ticks());
        } else {
            /* Update mouse cursor */
            int32_t mx, my;
            input_get_mouse_position(&mx, &my);

            if (mx != last_mx || my != last_my) {
                if (last_mx >= 0 && last_my >= 0) {
                    fb_fill_rect(last_mx, last_my, 12, 12, COLOR_CREAM);
                }
                draw_cursor(mx, my);
                last_mx = mx;
                last_my = my;
            }
        }

        __asm__ volatile("hlt");
    }
}
